### ISSUE TITLE
It crash in UIWebView (FLWebView) setScalesPageToFit:

### ISSUE THREAD

**Issue by eaiccc** [gowithfloat/FLWebView#3]
It crash in it when cordova relative class call webview.scalesPageToFit;
it seems alway call it self, and over the stack.
and I comment the method in UIWebView (FLWebView), It work.
I would test it for any other side effect

**Comment by steverichey** [comment]
Could you provide more information on the issue? This isn't intended to function as a wrapper for Cordova.

**Comment by steverichey** [comment]
Closing without further information.

**Comment by JohnDn** [comment]
Xcode 7.0.1 
Crashed in WKWebView+FLWKWebView.m
 - (void) loadRequestFromString: (NSString *) urlNameAsString

**Comment by steverichey** [comment]
This was fixed in [this](https://github.com/gowithfloat/FLWebView/pull/8) pull request.
