### ISSUE TITLE
Not working on ios 9?

### ISSUE THREAD

**Issue by ianfbrown** [gowithfloat/FLWebView#6]
Using xcode 7.0, this project works fine in the simulator for ios 8.1 (iPad 2), but after the splash screen it  gets stuck with a white screen for the simulator for ios 9.0 (iPad 2), and for a physical iPad Mini 2 running ios 9.0.1. Any idea where to start looking? Many thanks, Ian.

**Comment by ianfbrown** [comment]
Following on from feedback from Josh Kehn, with a similar issue for [JSMessageExample](https://github.com/joshkehn/JSMessageExample/issues/2), this is due to the new for ios 9: [App Transport Security](https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/).

The fix is to either upgrade the required website to the latest https, or to edit the Info.plist file to disable App Transport Security for individual websites (or even disable it entirely). To get FLWebView up and running again on ios 9, to access floatlearning.com, simply add the following to the Info.plist file:

    <key>NSAppTransportSecurity</key>
    <dict>
      <key>NSExceptionDomains</key>
      <dict>
        <key>floatlearning.com</key>
        <dict>
          
          <key>NSIncludesSubdomains</key>
          <true/>
          
          <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
          <true/>
          
          <key>NSTemporaryExceptionMinimumTLSVersion</key>
          <string>TLSv1.1</string>
        </dict>
      </dict>
    </dict>

as described on [Steven Peterson's blog](http://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/). He also has instructions for disabling App Transport Security entirely.

**Comment by steverichey** [comment]
Thanks for pointing this out, and tracking down the problem!

**Comment by avaiyakirtib** [comment]
yes Its not working in iOS 9 also in 9.2

**Comment by steverichey** [comment]
@avaiyakirtib: This is a consequence of App Transport Security. If you want to allow HTTP, just add `NSTemporaryExceptionAllowsInsecureHTTPLoads` to your plist.
